### ISSUE TITLE
There are RT tickets

### ISSUE THREAD

**Issue by eserte** [lab-measurement/Syntax-Highlight-Engine-Simple-Perl#2]
Are you aware of https://rt.cpan.org/Ticket/Display.html?id=110323 and maybe other RT tickets?

**Comment by kentfredric** [comment]
All existing RT ticks are either fixed in 0.05, or will be fixed if https://github.com/lab-measurement/Syntax-Highlight-Engine-Simple-Perl/pull/3 is merged.

**Comment by akhuettel** [comment]
All are fixed and closed now.
